package com.example.recyclerview.contents;

public class CapitalName {
    public String[] capital = {
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama",
            "Finfine",
            "Addis Ababa",
            "Kenya",
            "Bishoftu",
            "Adama"
    };
}
