package com.example.recyclerview.contents;

public class CountryName {
    public String[] country = {
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan",
            "Oromia",
            "Ethiopia",
            "Addis Ababa",
            "Kenya",
            "Sudan"
    };
}
